### ISSUE TITLE
pipot-server web pages is not loaded properly. 

### ISSUE THREAD

**Issue by VertexC** [PiPot/PiPot#11]
### Version
Pipot 0.6

### Encountered behaviour
After logged into PiPot, under /auth/manager. If go to other route. it will require the user to log in again, and never redirect to the right page. 

The issue is caused beacause login_require always get user=None, which means g.user is not stored correctly. There is a session in mod_auth/controllers.py and user_id is stored in that session, while the session is invisible when route changes.

### Log, with manually print user inside login_require
check on login require
The current user is, usrname bowenc
127.0.0.1 - - [20/Mar/2019 21:44:07] "GET /auth/manage HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 21:44:07] "GET /static/css/app.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 21:44:07] "GET /static/css/foundation.min.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 21:44:07] "GET /static/img/favicon/favicon-32x32.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 21:44:07] "GET /static/img/favicon/favicon-16x16.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 21:44:07] "GET /static/img/favicon/favicon-96x96.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 21:44:07] "GET /static/img/favicon/android-chrome-192x192.png HTTP/1.1" 200 -
check on login require
The current user is None
127.0.0.1 - - [20/Mar/2019 21:44:10] "GET /notifications HTTP/1.1" 302 -
/usr/src/pipot/server/mod_auth/controllers.py:87: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  form = LoginForm(request.form)
127.0.0.1 - - [20/Mar/2019 21:44:10] "GET /auth/login?next=config.notifications HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 21:44:10] "GET /static/css/app.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 21:44:10] "GET /static/css/foundation.min.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 21:44:10] "GET /static/img/favicon/favicon-32x32.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 21:44:10] "GET /static/img/favicon/favicon-16x16.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Mar/2019 21:44:10] "GET /static/img/favicon/favicon-96x96.png HTTP/1.1" 200 -

**Comment by bangpradyumna** [comment]
Can you elaborate on the steps to reproduce this problem. It did not log me out when I moved from /auth/manage to some other place like /services 
Did you run the server using nginx/pipot daemon or using run.py ?

**Comment by VertexC** [comment]
I was using run.py, and the server is set up on ubuntu.

**Comment by bangpradyumna** [comment]
Actually you need to use Raspberry Pi or any ARM architecture based machine.
Also, Use the daemon by typing `service pipot start`
