### ISSUE TITLE
How can I install and run PiPot? 

### ISSUE THREAD

**Issue by pyaada** [PiPot/PiPot#18]
### Version

_What version of PiPot are you using?_
Can't figure this out.

### Expected behaviour

_What did you expect to happen?_
Successful installation of PiPot 

### Encountered behaviour

_What happened instead?_
PiPot installer failed to create database. No error in log file. 

### Additional information

_Please enter any additional information you have (stacktraces, log files, ...)_
````
Welcome to the PiPot installer!

Detailed information will be written to /usr/src/pipot/pipot-server/install/PiPotInstall_2020-01-29_log.txt

-------------------------------
|   Installing dependencies   |
-------------------------------

* Updating package list        
* Installing nginx, python & pip      
* Use virtualenv /usr/src/pipot/pipot-env
* Update setuptools            
* Installing pip dependencies

-------------------------------
|   Configuration of PiPot    |
-------------------------------

In order to configure PiPot, we need some information from you. Please reply to the next questions:

Password of the 'root' user of MySQL: password 
mysql: [Warning] Using a password on the command line interface can be insecure.
Database name for storing data: pipot
Failed to create the database! Please check the installation log!
````

PiPot installer log file
[PiPotInstall_2020-01-29_log.txt.txt](https://github.com/PiPot/PiPot/files/4124209/PiPotInstall_2020-01-29_log.txt.txt)

**Comment by canihavesomecoffee** [comment]
What happens if you'd manually run the failing command?

Also, running the script with `/bin/bash -x install.sh` could yield additional info.

**Comment by canihavesomecoffee** [comment]
Closing as no reply came in. Feel free to re-open if you can provide an answer to the question I posed earlier.
