### ISSUE TITLE
Menu entries nesting

### ISSUE THREAD

**Issue by canihavesomecoffee** [PiPot/PiPot#4]
Currently we only allow one level of nesting in the menus, but that could change in the future.

Checks if a user has access to this should therefore be recursive.

Code section: https://github.com/PiPot/pipot-server/blob/70468cbad853ab3d3743f0e0d5831bfc4c0e36a9/decorators.py#L37

**Comment by bangpradyumna** [comment]
Issue solved with https://github.com/PiPot/pipot-server/commit/367b469fe702febd5f18fe7dce0daaffbd26edfe
and can be closed :)
