### ISSUE TITLE
Running server on non RPi platform

### ISSUE THREAD

**Issue by canihavesomecoffee** [PiPot/PiPot#6]
Currently the system is limited to run both the server and honeypots on Raspberry Pi's. While this shouldn't change for the latter, it sometimes (especially during image generation) is a bottleneck for the server.

Ideally the server should also be able to run on a general purpose Linux distribution, but changes will need to be made (and tests performed) to ensure that this doesn't break the image generation due to different platforms (ARM vs x86 for example).

**Comment by VertexC** [comment]
I have already fix the dependencies issues for it to be run under linux-gun(ubuntu) on aws. #10  While I still keep getting error "An error has occurred: b"CannotListenError: Couldn't listen on 18.222.168.54:1235: [Errno 99] Cannot assign requested addre"
Please look at log file for more information."

I should have opened the ports on my aws server. Any idea on how to resolve it? @canihavesomecoffee
